const SUCCESS = "SUCCESS";
const ERROR = "ERROR";
const TOGGLE_HIGHLIGHTER = "TOGGLE_HIGHLIGHTER";
const HIGHIGHTER_ON = "HIGHLIGHTER_ON";
const HIGHIGHTER_OFF = "HIGHLIGHTER_OFF";
const IS_HIGHLIGHTER_ON = "IS_HIGHLIGHTER_ON";
const CHANGE_COLOR = "CHANGE_COLOR";
const DEFAULT_COLORS = ["#ff6347", "#66ff47", "#47b5ff", "#ffc547"];