const TOGGLE_HIGHLIGHTER = "TOGGLE_HIGHLIGHTER";
const HIGHLIGHTER_TURNED_ON = "HIGHLIGHTER_TURNED_ON";
const HIGHLIGHTER_TURNED_OFF = "HIGHLIGHTER_TURNED_OFF";
const DELETE_HIGHLIGHT = "DELETE_HIGHLIGHT";
const ADDED_NEW_HIGHLIGHT = "ADDED_NEW_HIGHLIGHT";
const DELETED_HIGHLIGHT = "DELETED_HIGHLIGHT";
const CHANGE_COLOR = "CHANGE_COLOR";

const SUCCESS = "SUCCESS";
const ERROR = "ERROR";