const HIGHLIGHT_ON = "HIGHLIGHT_ON";
const HIGHLIGHT_OFF = "HIGHLIGHT_OFF";
const HIGHLIGHTER_TURNED_ON = "HIGHLIGHTER_TURNED_ON";
const HIGHLIGHTER_TURNED_OFF = "HIGHLIGHTER_TURNED_OFF";
const DELETE_HIGHLIGHT = "DELETE_HIGHLIGHT";
const ADDED_NEW_HIGHLIGHT = "ADDED_NEW_HIGHLIGHT";
const DELETED_HIGHLIGHT = "DELETED_HIGHLIGHT";
const ERROR = "ERROR";